services:
  - type: web
    name: ecommerce-backend
    env: docker
    repo: https://github.com/rAKES12345/ecommerce
    branch: delivery-module-pending
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile
    healthCheckPath: /
